AWSTemplateFormatVersion: '2010-09-09'
Description:
  Create S3 bucket, S3 bucket policy, S3 IAM policy, S3 IAM group, S3 IAM user,
  CloudFront distribution, Origin Access Control
Metadata:
  # Specify input parameter grouping and ordering
  "AWS::CloudFormation::Interface": 
    ParameterGroups: 
      - Label: 
          default: "Prefix"
        Parameters: 
          - Prefix
Parameters:
  Prefix:
    Description: "Prefix for resource name"
    Type: String
    Default: "dev-" # Prefix for resource name
    AllowedValues:
      - dev-
      - stg-
      - prd-
  BucketName:
    Description: "Bucket name"
    Type: String
    Default: "s3bucket"
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub '${Prefix}${BucketName}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      VersioningConfiguration:
        Status: Suspended
  S3BucketPolicy:
      Type: 'AWS::S3::BucketPolicy'
      Properties:
        Bucket: !Ref S3Bucket
        PolicyDocument:
          Id: PolicyForCloudFrontPrivateContent
          Version: 2008-10-17
          Statement:
            - Sid: AllowCloudFrontServicePrincipal
              Effect: Allow
              Principal:
                Service: cloudfront.amazonaws.com
              Action: s3:GetObject
              Resource: !Sub ${S3Bucket.Arn}/*
              Condition:
                StringEquals:
                  AWS:SourceArn: 
                    - !Join 
                      - ''
                      - - !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/'
                        - !Ref CloudFront
  S3IAMPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Sub ${Prefix}S3IAMPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:ListAllMyBuckets'
            Resource: 
              - 'arn:aws:s3:::*'
          - Effect: Allow
            Action:
              - 's3:ListBucket'
            Resource: 
              - !Sub 'arn:aws:s3:::${BucketName}'
          - Effect: Allow
            Action:
              - 's3:PutObject'
              - 's3:DeleteObject'
              - 's3:GetObject'
            Resource: 
              - !Sub 'arn:aws:s3:::${BucketName}/*'
      Groups:
        - !Ref S3IAMGroup
  S3IAMGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: !Sub '${Prefix}S3AccessGroup'
  S3IAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: !Sub '${Prefix}S3AccessUser'
      Groups:
        - !Ref S3IAMGroup
  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig:
        DefaultCacheBehavior: 
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized
          TargetOriginId: S3
          ViewerProtocolPolicy: allow-all # HTTP and HTTPS only
          Compress: true
        Enabled: true
        Origins: # Contains information about the origins for this distribution.
          - DomainName: !GetAtt S3Bucket.RegionalDomainName
            Id: S3
            OriginAccessControlId: !GetAtt OAC.Id
            S3OriginConfig: 
              OriginAccessIdentity: ''
        PriceClass: PriceClass_200
        HttpVersion: http2and3
        Comment: !Sub '${Prefix}CloudFront'
  OAC: 
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig:
        Description: Access Control
        Name: !Sub '${Prefix}CloudFrontOAC'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4